developmentBranch: Test
localStorageBranchTargets:
  features/dev/createsCases: Test
installedApps:
  - git
scratchOrgAlias: null
scratchOrgUsername: null
sfdxPluginsStdout: "packaging \e[2m1.27.3\e[22m\nsfdmu \e[2m4.32.1\e[22m\nsfdx-essentials \e[2m2.12.0\e[22m\nsfdx-git-delta \e[2m5.30.0\e[22m\nsfdx-hardis \e[2m4.17.1\e[22m\ntexei-sfdx-plugin \e[2m2.2.0\e[22m\n\e[2m\e[22m\n\e[2mUninstalled JIT Plugins:\e[22m\ncommunity \e[2m2.4.9\e[22m\ncustom-metadata \e[2m2.2.12\e[22m\ndev \e[2m1.3.2\e[22m\ndevops-center \e[2m1.2.4\e[22m\nenv \e[2m3.0.1\e[22m\nfunctions \e[2m1.22.9\e[22m\nsignups \e[2m1.5.6\e[22m\n@salesforce/sfdx-plugin-lwc-test \e[2m1.1.1\e[22m\n@salesforce/sfdx-scanner \e[2m3.18.0\e[22m\n"
mergeRequests:
  - branch: features/dev/createsCases
